### ISSUE TITLE
(chore) Bump PaperAPI to 1.18.1-R0.1-SNAPSHOT

### ISSUE THREAD

**Issue by GoliathLabs** [mikroskeem/Adminchatter#7]
Hello,
we are currently still using PaperAPI version 1.16.1-R0.1-SNAPSHOT and might upgrade to 1.18.1 in the future.

**Comment by mikroskeem** [comment]
It works fine on 1.18.1 Paper right now, and new API does not affect this plugin significantly yet.

However, I've seen that there's [AsyncChatEvent](https://papermc.io/javadocs/paper/1.18/io/papermc/paper/event/player/AsyncChatEvent.html) now (Bukkit's AsyncPlayerChatEvent is deprecated), so perhaps in next few minor/major releases I might need to update it.
